# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username if you have one
patreon: # Replace with your Patreon username if you have one
open_collective: # Replace with your Open Collective username if you have one
ko_fi: # Replace with your Ko-fi username if you have one
tidelift: # Replace with your Tidelift package name if you have one
community_bridge: # Replace with your Community Bridge project slug if you have one
liberapay: # Replace with your Liberapay username if you have one
issuehunt: # Replace with your IssueHunt username if you have one
lfx_crowdfunding: # Replace with your LFX Crowdfunding project slug if you have one
polar: # Replace with your Polar username if you have one
buy_me_a_coffee: prot10
custom: ['https://paypal.me/andreaprotani99']
